name: test_easy_rental
description: "A modern car rental app built with Flutter, featuring user authentication, car browsing, and booking functionality."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.2.7
  dio: ^5.7.0
  # Secure Storage
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  # Network Image Caching
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/car_rental.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/car_rental.png"
    background_color: "#343434"
    theme_color: "#343434"
  windows:
    generate: true
    image_path: "assets/images/car_rental.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/car_rental.png"

